"""initial migration

Revision ID: 2caad88db563
Revises: 
Create Date: 2024-10-27 16:13:41.853672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2caad88db563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_desigm__com', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technology_stack', sa.String(length=80), nullable=False))

    with op.batch_alter_table('links_desigm_not__com', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technology_stack', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_desigm_not__com', schema=None) as batch_op:
        batch_op.drop_column('technology_stack')

    with op.batch_alter_table('links_desigm__com', schema=None) as batch_op:
        batch_op.drop_column('technology_stack')

    # ### end Alembic commands ###
